// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[association]` — how the OS should treat it.
 */
export type Association = { 
/**
 * RFC 6838 media type. Vendor tree (`vnd.`) strongly recommended.
 */
mime: string, 
/**
 * Path to a source PNG, relative to the spec file. Core never opens it —
 * the caller reads the bytes and hands them to [`crate::IconSet`].
 */
icon?: string | null, 
/**
 * Executable name, absolute path, or macOS bundle id.
 */
handler?: string | null, 
/**
 * Argument template. `%1` is normalised per platform (`%f` on Linux).
 */
handler_args: string, };
