// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the bytes are wrapped in. Informs the magic rule and the generated
 * README; it does **not** cause filekind to generate a parser.
 */
export type Container = "zip" | "sqlite" | "text" | "binary" | "none";
