// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Severity } from "./Severity";

/**
 * One validation finding, addressed to a specific field so the GUI can put a
 * red underline in the right box.
 */
export type Diagnostic = { severity: Severity, 
/**
 * Dotted path, e.g. `format.extension`.
 */
field: string, message: string, 
/**
 * What to do about it. Present whenever there is an obvious fix.
 */
hint?: string | null, };
