// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Container } from "./Container";

/**
 * `[format]` — what the file *is*.
 */
export type Format = { 
/**
 * Human-readable name, shown in OS UI ("Londo Save").
 */
name: string, 
/**
 * Extension without a leading dot. Validated hard; see [`crate::validate`].
 */
extension: string, 
/**
 * One-line description, shown in Explorer's Type column and Nautilus.
 */
description: string, 
/**
 * Optional escaped-byte string matched at offset 0, e.g. `"LNDO\x01"`.
 */
magic?: string | null, container: Container, version?: string | null, };
