// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[linux]` overrides.
 */
export type LinuxOpts = { desktop_categories: Array<string>, generic_name?: string | null, 
/**
 * Emitted as `NoDisplay=true` — the handler registers for the type but
 * does not clutter the application menu.
 */
no_display: boolean, };
