// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[macos]` overrides.
 */
export type MacosOpts = { bundle_id?: string | null, uti_conforms_to: Array<string>, 
/**
 * Override the exported UTI. Defaults to `<bundle_id>.<extension>`.
 */
uti?: string | null, };
