// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Windows `PerceivedType`. Drives grouping in Explorer and the default
 * preview handler.
 */
export type PerceivedType = "text" | "image" | "audio" | "video" | "compressed" | "document" | "system" | "application" | "gamemedia" | "contacts";
