// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[schema]` — v0.5 Kaitai seam.
 */
export type SchemaOpts = { 
/**
 * Path to a `.ksy`, relative to the spec file. Core never opens it.
 */
kaitai?: string | null, 
/**
 * Target languages for `kaitai-struct-compiler -t`.
 */
languages?: Array<string>, };
