// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Association } from "./Association";
import type { Format } from "./Format";
import type { LinuxOpts } from "./LinuxOpts";
import type { MacosOpts } from "./MacosOpts";
import type { SchemaOpts } from "./SchemaOpts";
import type { Targets } from "./Targets";
import type { WindowsOpts } from "./WindowsOpts";

/**
 * A parsed `.filekind` spec.
 */
export type Spec = { format: Format, association: Association, targets: Targets, windows: WindowsOpts, linux: LinuxOpts, macos: MacosOpts, 
/**
 * v0.5, optional. filekind is the association layer; Kaitai is the format
 * layer. This table is the seam between them and nothing more.
 */
schema?: SchemaOpts | null, };
