// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[targets]` — which platforms to emit for.
 */
export type Targets = { windows: boolean, linux: boolean, 
/**
 * Off by default: a UTI declaration without a signed app bundle does
 * nothing. See the warning `validate` emits when you turn it on.
 */
macos: boolean, };
