// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PerceivedType } from "./PerceivedType";

/**
 * `[windows]` overrides.
 */
export type WindowsOpts = { 
/**
 * Programmatic identifier. Defaults to a value derived from the MIME
 * vendor tree; see [`Spec::progid`].
 */
progid?: string | null, perceived_type?: PerceivedType | null, 
/**
 * Where the `.ico` will live once installed, e.g.
 * `C:\\Program Files\\Londo\\icon.ico`.
 *
 * A loose `.reg` file cannot know your install directory, and writing a
 * guess would register an icon path that does not exist. When this is
 * unset filekind points `DefaultIcon` at the handler executable instead,
 * and if there is no handler it omits the key and says so in the
 * generated README. The Inno and NSIS snippets do not need this — an
 * installer knows where it put things.
 */
icon_path?: string | null, 
/**
 * Extra verbs beyond `open`, e.g. `edit = "notepad.exe \"%1\""`.
 */
verbs?: { [key in string]: string }, };
