//! Turning a [`Spec`] into [`Artifact`]s.
//!
//! Everything here is pure. `generate` takes a spec plus whatever bytes the
//! caller has already read (an icon, a Kaitai schema) and returns a `Vec` of
//! files that do not exist yet.

use serde::Serialize;

use crate::artifact::{Artifact, ArtifactKind, Platform};
use crate::error::Result;
use crate::icon::IconSet;
use crate::spec::Spec;

pub mod escape;
mod linux;
mod macos;
mod packaging;
mod templates;
mod universal;
mod windows;

/// Where the generated artifacts install to.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize)]
pub enum Scope {
    /// `HKEY_CURRENT_USER` and `~/.local/share`. No elevation, and the default
    /// for the obvious reason: privilege you did not need is privilege you can
    /// lose.
    #[default]
    User,
    /// `HKEY_LOCAL_MACHINE` and `/usr/share`. Opt-in and explicit.
    System,
}

impl Scope {
    pub fn is_system(self) -> bool {
        self == Scope::System
    }

    /// Registry hive for this scope.
    pub fn hive(self) -> &'static str {
        match self {
            Scope::User => "HKEY_CURRENT_USER",
            Scope::System => "HKEY_LOCAL_MACHINE",
        }
    }

    /// Abbreviated hive, for Inno and NSIS.
    pub fn hive_short(self) -> &'static str {
        match self {
            Scope::User => "HKCU",
            Scope::System => "HKLM",
        }
    }

    /// `xdg-mime --mode` value.
    pub fn xdg_mode(self) -> &'static str {
        match self {
            Scope::User => "user",
            Scope::System => "system",
        }
    }
}

/// Everything the caller must supply that core refuses to read for itself.
#[derive(Debug, Clone, Default)]
pub struct GenerateOptions {
    pub scope: Scope,
    /// Rendered icons. `None` means no icon was configured or the caller chose
    /// not to read it; generation still succeeds, minus the icon artifacts.
    pub icon: Option<IconSet>,
    /// Emit `.deb` and `.rpm` packaging alongside the loose files.
    pub packaging: bool,
    /// Emit a skeleton `.app` bundle on macOS (`--stub-app`).
    pub stub_app: bool,
    /// Contents of the `.ksy` referenced by `[schema]`, if the caller read it.
    pub kaitai_schema: Option<String>,
}

impl GenerateOptions {
    /// The defaults `filekind build` uses: user scope, packaging on, no stub app.
    pub fn build_defaults() -> Self {
        GenerateOptions {
            packaging: true,
            ..Default::default()
        }
    }
}

/// Generate every artifact for the targets the spec enables.
///
/// Validation errors are *not* checked here — call [`crate::validate`] first.
/// Generation of a slightly wrong spec is still useful in the GUI, where the
/// preview pane needs to render something while the user is mid-keystroke.
pub fn generate(spec: &Spec, opts: &GenerateOptions) -> Result<Vec<Artifact>> {
    let mut out = Vec::new();

    if spec.targets.windows {
        windows::generate(spec, opts, &mut out)?;
    }
    if spec.targets.linux {
        linux::generate(spec, opts, &mut out)?;
    }
    if spec.targets.macos {
        macos::generate(spec, opts, &mut out)?;
    }
    universal::generate(spec, opts, &mut out)?;

    #[cfg(feature = "kaitai")]
    crate::kaitai::generate(spec, opts, &mut out)?;

    out.sort_by(|a, b| (a.platform, a.kind, &a.path).cmp(&(b.platform, b.kind, &b.path)));
    Ok(out)
}

/// Generate only the artifacts for one platform. Used by `filekind build
/// --target windows` and by the GUI's preview tabs.
pub fn generate_for(
    spec: &Spec,
    opts: &GenerateOptions,
    platform: Platform,
) -> Result<Vec<Artifact>> {
    let mut out = Vec::new();
    match platform {
        Platform::Windows => windows::generate(spec, opts, &mut out)?,
        Platform::Linux => linux::generate(spec, opts, &mut out)?,
        Platform::Macos => macos::generate(spec, opts, &mut out)?,
        Platform::Universal => universal::generate(spec, opts, &mut out)?,
    }
    out.sort_by(|a, b| (a.kind, &a.path).cmp(&(b.kind, &b.path)));
    Ok(out)
}

/// Pick one artifact out of a generated set — `filekind preview`.
pub fn find(artifacts: &[Artifact], platform: Platform, kind: ArtifactKind) -> Option<&Artifact> {
    artifacts
        .iter()
        .find(|a| a.platform == platform && a.kind == kind)
}

/// The header comment stamped onto every generated text artifact, in whatever
/// comment syntax the format uses.
///
/// A `.reg` file on someone's desktop two years from now should say where it
/// came from and that editing it is pointless.
pub(crate) fn banner(spec: &Spec, comment: &str) -> String {
    let mut s = String::new();
    for line in [
        format!("Generated by filekind {} — do not edit.", crate::VERSION),
        format!("Source: {} (.{})", spec.format.name, spec.format.extension),
        "Regenerate with: filekind build".to_string(),
    ] {
        if !comment.is_empty() {
            s.push_str(comment);
            s.push(' ');
        }
        s.push_str(&line);
        s.push('\n');
    }
    s
}
